export interface SizePreset {
  id: string;
  label: string;
  amount: number;
  unit: "g" | "ml" | "pc";
  icon: string;
}

export const SIZE_PRESETS: Record<string, SizePreset[]> = {
  FOOD: [
    { id: "tiny", label: "Tiny", amount: 50, unit: "g", icon: "🤏" },
    { id: "small", label: "Small", amount: 100, unit: "g", icon: "🥄" },
    { id: "medium", label: "Medium", amount: 200, unit: "g", icon: "🍽️" },
    { id: "large", label: "Large", amount: 300, unit: "g", icon: "🍲" },
    { id: "xl", label: "XL", amount: 450, unit: "g", icon: "🍱" },
  ],
  DRINK: [
    { id: "small", label: "Small", amount: 200, unit: "ml", icon: "☕" },
    { id: "medium", label: "Medium", amount: 330, unit: "ml", icon: "🥤" },
    { id: "large", label: "Large", amount: 500, unit: "ml", icon: "🥛" },
    { id: "xl", label: "XL", amount: 1000, unit: "ml", icon: "🏺" },
  ],
  UNIT: [
    { id: "half", label: "Half", amount: 0.5, unit: "pc", icon: "0.5" },
    { id: "one", label: "1 Unit", amount: 1, unit: "pc", icon: "1" },
    { id: "two", label: "2 Units", amount: 2, unit: "pc", icon: "2" },
    { id: "three", label: "3 Units", amount: 3, unit: "pc", icon: "3" },
  ],
  SUGAR: [
    { id: "one-spoon", label: "1 Spoon", amount: 1, unit: "pc", icon: "🥄" },
    { id: "two-spoons", label: "2 Spoons", amount: 2, unit: "pc", icon: "🥄" },
    {
      id: "three-spoons",
      label: "3 Spoons",
      amount: 3,
      unit: "pc",
      icon: "🥄",
    },
  ],
  SPOON: [
    { id: "one-tbsp", label: "1 tbsp", amount: 1, unit: "pc", icon: "🥄" },
    { id: "two-tbsp", label: "2 tbsp", amount: 2, unit: "pc", icon: "🥄" },
    { id: "three-tbsp", label: "3 tbsp", amount: 3, unit: "pc", icon: "🥄" },
  ],
};

export interface Category {
  id: number;
  name: string;
  nameAr: string;
  icon: string;
  popular?: boolean;
}

export interface Food {
  id: string;
  categoryId: number; // Foreign Key to Category
  name: string;
  nameAr: string;
  icon: string;
  caloriesPer100: number;
  proteinPer100: number;
  carbsPer100: number;
  fatPer100: number;
  sizeType: "FOOD" | "DRINK" | "UNIT" | "SUGAR" | "SPOON";
  isRawCookedToggle?: boolean;
  rawMultiplier?: number;
  weightPerUnit?: number; // Optional: grams per piece
}

export const CATEGORIES: Category[] = [
  { id: 1, name: "Proteins", nameAr: "بروتين", icon: "🥩", popular: true },
  { id: 13, name: "Salads", nameAr: "سلطات", icon: "🥗", popular: true },
  { id: 3, name: "Carbs", nameAr: "كربوهيدرات", icon: "🍚", popular: true },
  {
    id: 20,
    name: "Traditional Egyptian",
    nameAr: "أكل مصري",
    icon: "🇪🇬",
    popular: true,
  },

  { id: 4, name: "Fruits", nameAr: "فاكهة", icon: "🍎" },
  { id: 6, name: "Drinks", nameAr: "مشروبات", icon: "🥤" },
  { id: 17, name: "Supplements", nameAr: "مكملات", icon: "💪" },
  { id: 5, name: "Desserts", nameAr: "حلويات", icon: "🍰" },

  { id: 10, name: "Dairy", nameAr: "ألبان", icon: "🧀" },
  { id: 12, name: "Snacks", nameAr: "مكسرات", icon: "🥜" },
  { id: 19, name: "Ramadan Foods", nameAr: "رمضان", icon: "🌙" },
  { id: 18, name: "Kids Meals", nameAr: "أطفال", icon: "👶" },

  // Remaining background categories if needed
  { id: 2, name: "Middle East Staples", nameAr: "أكلات شعبية", icon: "🥙" },
  { id: 7, name: "Sauces & Extras", nameAr: "صوصات وإضافات", icon: "🍯" },
  { id: 8, name: "Fast Food", nameAr: "وجبات سريعة", icon: "🍔" },
  { id: 9, name: "Seafood", nameAr: "مأكولات بحرية", icon: "🦐" },
  { id: 11, name: "Breakfast", nameAr: "فطار", icon: "🍳" },
  { id: 14, name: "Street Food", nameAr: "أكل الشارع", icon: "🌮" },
  { id: 15, name: "Bakery", nameAr: "مخبوزات", icon: "🥖" },
  { id: 16, name: "Frozen Foods", nameAr: "أطعمة مجمدة", icon: "🧊" },
  { id: 21, name: "Eid Desserts", nameAr: "حلويات العيد", icon: "🎉" },
  { id: 22, name: "Grills", nameAr: "مشويات", icon: "🔥" },
  { id: 23, name: "Rice Dishes", nameAr: "أطباق الأرز", icon: "🍛" },
  { id: 24, name: "Sandwiches", nameAr: "ساندوتشات", icon: "🥪" },
];

export const FOODS: Food[] = [
  // --- Proteins (Category 1) ---
  {
    id: "p1",
    categoryId: 1,
    name: "Chicken Breast",
    nameAr: "صدور دجاج",
    icon: "🍗",
    caloriesPer100: 165,
    proteinPer100: 31,
    carbsPer100: 0,
    fatPer100: 3.6,
    sizeType: "FOOD",
    isRawCookedToggle: true,
  },
  {
    id: "p2",
    categoryId: 1,
    name: "Egg",
    nameAr: "بيض",
    icon: "🥚",
    caloriesPer100: 155,
    proteinPer100: 13,
    carbsPer100: 1.1,
    fatPer100: 11,
    sizeType: "UNIT",
    weightPerUnit: 50,
  },
  {
    id: "p4",
    categoryId: 1,
    name: "Beef (Lean)",
    nameAr: "لحم بقري",
    icon: "🥩",
    caloriesPer100: 250,
    proteinPer100: 26,
    carbsPer100: 0,
    fatPer100: 15,
    sizeType: "FOOD",
    isRawCookedToggle: true,
  },
  {
    id: "me1",
    categoryId: 1,
    name: "Chicken Shawarma",
    nameAr: "شاورما دجاج",
    icon: "🌯",
    caloriesPer100: 220,
    proteinPer100: 18,
    carbsPer100: 12,
    fatPer100: 10,
    sizeType: "FOOD",
  },
  {
    id: "me2",
    categoryId: 1,
    name: "Beef Kofta",
    nameAr: "كفتة مشوية",
    icon: "🍢",
    caloriesPer100: 280,
    proteinPer100: 16,
    carbsPer100: 4,
    fatPer100: 22,
    sizeType: "FOOD",
  },
  {
    id: "me3",
    categoryId: 1,
    name: "Grilled Fish",
    nameAr: "سمك مشوي",
    icon: "🐟",
    caloriesPer100: 150,
    proteinPer100: 22,
    carbsPer100: 0,
    fatPer100: 6,
    sizeType: "FOOD",
  },
  {
    id: "me4",
    categoryId: 1,
    name: "Lentil Soup",
    nameAr: "شوربة عدس",
    icon: "🥣",
    caloriesPer100: 85,
    proteinPer100: 6,
    carbsPer100: 14,
    fatPer100: 1,
    sizeType: "FOOD",
  },
  {
    id: "me5",
    categoryId: 1,
    name: "Liver (Alexandrian)",
    nameAr: "كبدة إسكندراني",
    icon: "🥘",
    caloriesPer100: 210,
    proteinPer100: 24,
    carbsPer100: 4,
    fatPer100: 10,
    sizeType: "FOOD",
  },
  {
    id: "me23",
    categoryId: 1,
    name: "Tilapia Fish",
    nameAr: "سمك بلطي",
    icon: "🐟",
    caloriesPer100: 128,
    proteinPer100: 26,
    carbsPer100: 0,
    fatPer100: 3,
    sizeType: "FOOD",
    isRawCookedToggle: true,
  },

  // --- Middle East Staples (Category 2) ---
  {
    id: "me6",
    categoryId: 2,
    name: "Ful Medames",
    nameAr: "فول مدمس",
    icon: "🥣",
    caloriesPer100: 110,
    proteinPer100: 8,
    carbsPer100: 20,
    fatPer100: 0.5,
    sizeType: "FOOD",
  },
  {
    id: "me7",
    categoryId: 2,
    name: "Falafel (Ta'ameya)",
    nameAr: "طعمية",
    icon: "🧆",
    caloriesPer100: 330,
    proteinPer100: 13,
    carbsPer100: 30,
    fatPer100: 18,
    sizeType: "UNIT",
    weightPerUnit: 25,
  },
  {
    id: "me8",
    categoryId: 2,
    name: "Koshary",
    nameAr: "كشري مصري",
    icon: "🥣",
    caloriesPer100: 180,
    proteinPer100: 6,
    carbsPer100: 35,
    fatPer100: 2,
    sizeType: "FOOD",
  },
  {
    id: "me9",
    categoryId: 2,
    name: "Molokhia",
    nameAr: "ملوخية",
    icon: "🥣",
    caloriesPer100: 45,
    proteinPer100: 3,
    carbsPer100: 6,
    fatPer100: 1,
    sizeType: "FOOD",
  },
  {
    id: "me10",
    categoryId: 2,
    name: "Mahshi (Grape Leaves)",
    nameAr: "محشي ورق عنب",
    icon: "🥬",
    caloriesPer100: 170,
    proteinPer100: 4,
    carbsPer100: 28,
    fatPer100: 5,
    sizeType: "FOOD",
  },
  {
    id: "me11",
    categoryId: 2,
    name: "Macarona Bechamel",
    nameAr: "مكرونة بالبشاميل",
    icon: "🍝",
    caloriesPer100: 240,
    proteinPer100: 12,
    carbsPer100: 24,
    fatPer100: 11,
    sizeType: "FOOD",
  },
  {
    id: "me12",
    categoryId: 2,
    name: "Hawawshi",
    nameAr: "حواوشي",
    icon: "🥙",
    caloriesPer100: 300,
    proteinPer100: 14,
    carbsPer100: 22,
    fatPer100: 18,
    sizeType: "FOOD",
  },

  // --- Carbs (Category 3) ---
  {
    id: "c1",
    categoryId: 3,
    name: "White Rice",
    nameAr: "أرز أبيض",
    icon: "🍚",
    caloriesPer100: 130,
    proteinPer100: 2.7,
    carbsPer100: 28,
    fatPer100: 0.3,
    sizeType: "FOOD",
    isRawCookedToggle: true,
  },
  {
    id: "c2",
    categoryId: 3,
    name: "Potato",
    nameAr: "بطاطس",
    icon: "🥔",
    caloriesPer100: 77,
    proteinPer100: 2,
    carbsPer100: 17,
    fatPer100: 0.1,
    sizeType: "FOOD",
  },
  {
    id: "me13",
    categoryId: 3,
    name: "Baladi Bread",
    nameAr: "عيش بلدي",
    icon: "🫓",
    caloriesPer100: 250,
    proteinPer100: 9,
    carbsPer100: 52,
    fatPer100: 1,
    sizeType: "UNIT",
    weightPerUnit: 90,
  },
  {
    id: "c4",
    categoryId: 3,
    name: "Oats",
    nameAr: "شوفان",
    icon: "🥣",
    caloriesPer100: 389,
    proteinPer100: 16.9,
    carbsPer100: 66,
    fatPer100: 6.9,
    sizeType: "FOOD",
  },
  {
    id: "c11",
    categoryId: 3,
    name: "Vermicelli Rice",
    nameAr: "أرز بالشعيرية",
    icon: "🍚",
    caloriesPer100: 150,
    proteinPer100: 3,
    carbsPer100: 30,
    fatPer100: 2,
    sizeType: "FOOD",
  },

  // --- Veggies & Fruits (Category 4) ---
  {
    id: "v1",
    categoryId: 4,
    name: "Broccoli",
    nameAr: "بروكلي",
    icon: "🥦",
    caloriesPer100: 34,
    proteinPer100: 2.8,
    carbsPer100: 7,
    fatPer100: 0.4,
    sizeType: "FOOD",
  },
  {
    id: "v2",
    categoryId: 4,
    name: "Spinach",
    nameAr: "سبانخ",
    icon: "🍃",
    caloriesPer100: 23,
    proteinPer100: 2.9,
    carbsPer100: 3.6,
    fatPer100: 0.4,
    sizeType: "FOOD",
  },
  {
    id: "fr1",
    categoryId: 4,
    name: "Apple",
    nameAr: "تفاح",
    icon: "🍎",
    caloriesPer100: 52,
    proteinPer100: 0.3,
    carbsPer100: 14,
    fatPer100: 0.2,
    sizeType: "UNIT",
    weightPerUnit: 180,
  },
  {
    id: "fr8",
    categoryId: 4,
    name: "Orange",
    nameAr: "برتقال",
    icon: "🍊",
    caloriesPer100: 47,
    proteinPer100: 0.9,
    carbsPer100: 12,
    fatPer100: 0.1,
    sizeType: "UNIT",
    weightPerUnit: 150,
  },
  {
    id: "me14",
    categoryId: 4,
    name: "Dates",
    nameAr: "بلح / تمر",
    icon: "🌴",
    caloriesPer100: 280,
    proteinPer100: 2,
    carbsPer100: 75,
    fatPer100: 0.4,
    sizeType: "UNIT",
    weightPerUnit: 10,
  },

  // --- Desserts (Category 5) ---
  {
    id: "me31",
    categoryId: 5,
    name: "Baklava",
    nameAr: "بقلاوة",
    icon: "🥮",
    caloriesPer100: 430,
    proteinPer100: 6,
    carbsPer100: 50,
    fatPer100: 25,
    sizeType: "FOOD",
  },
  {
    id: "me15",
    categoryId: 5,
    name: "Kunafa",
    nameAr: "كنافة",
    icon: "🍯",
    caloriesPer100: 450,
    proteinPer100: 5,
    carbsPer100: 60,
    fatPer100: 22,
    sizeType: "FOOD",
  },
  {
    id: "me16",
    categoryId: 5,
    name: "Basbousa",
    nameAr: "بسبوسة",
    icon: "🍰",
    caloriesPer100: 380,
    proteinPer100: 4,
    carbsPer100: 55,
    fatPer100: 18,
    sizeType: "FOOD",
  },
  {
    id: "me17",
    categoryId: 5,
    name: "Om Ali",
    nameAr: "أم علي",
    icon: "🥣",
    caloriesPer100: 320,
    proteinPer100: 8,
    carbsPer100: 35,
    fatPer100: 18,
    sizeType: "FOOD",
  },
  {
    id: "me18",
    categoryId: 5,
    name: "Rice Pudding",
    nameAr: "أرز باللبن",
    icon: "🥣",
    caloriesPer100: 140,
    proteinPer100: 4,
    carbsPer100: 22,
    fatPer100: 4,
    sizeType: "FOOD",
  },
  {
    id: "me24",
    categoryId: 5,
    name: "Plain Chocolate",
    nameAr: "شوكلاتة سادة",
    icon: "🍫",
    caloriesPer100: 535,
    proteinPer100: 8,
    carbsPer100: 60,
    fatPer100: 30,
    sizeType: "FOOD",
  },
  {
    id: "me25",
    categoryId: 5,
    name: "Dark Chocolate",
    nameAr: "شوكلاتة خام",
    icon: "🍫",
    caloriesPer100: 598,
    proteinPer100: 8,
    carbsPer100: 46,
    fatPer100: 43,
    sizeType: "FOOD",
  },

  // --- Drinks (Category 6) ---
  {
    id: "me19",
    categoryId: 6,
    name: "Hibiscus (Karkadeh)",
    nameAr: "كركديه",
    icon: "🌺",
    caloriesPer100: 35,
    proteinPer100: 0,
    carbsPer100: 9,
    fatPer100: 0,
    sizeType: "DRINK",
  },
  {
    id: "me20",
    categoryId: 6,
    name: "Sahlab",
    nameAr: "سحلب",
    icon: "🥛",
    caloriesPer100: 120,
    proteinPer100: 3,
    carbsPer100: 20,
    fatPer100: 4,
    sizeType: "DRINK",
  },
  {
    id: "me21",
    categoryId: 6,
    name: "Turkish Coffee",
    nameAr: "قهوة تركي",
    icon: "☕",
    caloriesPer100: 5,
    proteinPer100: 0.5,
    carbsPer100: 0.5,
    fatPer100: 0,
    sizeType: "DRINK",
  },
  {
    id: "me22",
    categoryId: 6,
    name: "Mango Juice",
    nameAr: "عصير مانجو",
    icon: "🥭",
    caloriesPer100: 60,
    proteinPer100: 0.5,
    carbsPer100: 15,
    fatPer100: 0,
    sizeType: "DRINK",
  },
  {
    id: "d2",
    categoryId: 6,
    name: "Milk (Whole)",
    nameAr: "لبن كامل الدسم",
    icon: "🥛",
    caloriesPer100: 61,
    proteinPer100: 3.2,
    carbsPer100: 4.8,
    fatPer100: 3.3,
    sizeType: "DRINK",
  },

  // --- Sauces & Extras (Category 7) ---
  {
    id: "s1",
    categoryId: 7,
    name: "Sugar (Normal)",
    nameAr: "سكر عادي",
    icon: "🥄",
    caloriesPer100: 387,
    proteinPer100: 0,
    carbsPer100: 100,
    fatPer100: 0,
    sizeType: "SUGAR",
    weightPerUnit: 5,
  },
  {
    id: "s2",
    categoryId: 7,
    name: "Sugar (Diet)",
    nameAr: "سكر دايت",
    icon: "🌿",
    caloriesPer100: 0,
    proteinPer100: 0,
    carbsPer100: 0,
    fatPer100: 0,
    sizeType: "SUGAR",
    weightPerUnit: 1,
  },
  {
    id: "s3",
    categoryId: 7,
    name: "Honey",
    nameAr: "عسل",
    icon: "🍯",
    caloriesPer100: 304,
    proteinPer100: 0.3,
    carbsPer100: 82,
    fatPer100: 0,
    sizeType: "SUGAR",
    weightPerUnit: 7,
  },
  {
    id: "s4",
    categoryId: 7,
    name: "Ketchup",
    nameAr: "كاتشب",
    icon: "🍅",
    caloriesPer100: 112,
    proteinPer100: 1.3,
    carbsPer100: 26,
    fatPer100: 0.1,
    sizeType: "SPOON",
    weightPerUnit: 15,
  },
  {
    id: "s5",
    categoryId: 7,
    name: "Mayonnaise",
    nameAr: "مايونيز",
    icon: "🥚",
    caloriesPer100: 680,
    proteinPer100: 1,
    carbsPer100: 0.6,
    fatPer100: 75,
    sizeType: "SPOON",
    weightPerUnit: 15,
  },
  {
    id: "s6",
    categoryId: 7,
    name: "Mustard",
    nameAr: "مستردة",
    icon: "🥣",
    caloriesPer100: 66,
    proteinPer100: 4,
    carbsPer100: 8,
    fatPer100: 3,
    sizeType: "SPOON",
    weightPerUnit: 15,
  },
  {
    id: "s7",
    categoryId: 7,
    name: "Tahini",
    nameAr: "طحينة",
    icon: "🥣",
    caloriesPer100: 595,
    proteinPer100: 17,
    carbsPer100: 21,
    fatPer100: 54,
    sizeType: "SPOON",
    weightPerUnit: 15,
  },
  {
    id: "s8",
    categoryId: 7,
    name: "Garlic Sauce (Toum)",
    nameAr: "ثومية",
    icon: "🧄",
    caloriesPer100: 600,
    proteinPer100: 1,
    carbsPer100: 5,
    fatPer100: 65,
    sizeType: "SPOON",
    weightPerUnit: 15,
  },
  {
    id: "s9",
    categoryId: 7,
    name: "Olive Oil",
    nameAr: "زيت زيتون",
    icon: "🫒",
    caloriesPer100: 884,
    proteinPer100: 0,
    carbsPer100: 0,
    fatPer100: 100,
    sizeType: "SPOON",
    weightPerUnit: 14,
  },
  {
    id: "s10",
    categoryId: 7,
    name: "Pomegranate Molasses",
    nameAr: "دبس رمان",
    icon: "🍯",
    caloriesPer100: 300,
    proteinPer100: 0,
    carbsPer100: 75,
    fatPer100: 0,
    sizeType: "SPOON",
    weightPerUnit: 20,
  },
  {
    id: "s11",
    categoryId: 7,
    name: "Butter",
    nameAr: "زبدة",
    icon: "🧈",
    caloriesPer100: 717,
    proteinPer100: 0.9,
    carbsPer100: 0.1,
    fatPer100: 81,
    sizeType: "SPOON",
    weightPerUnit: 14,
  },
  {
    id: "s12",
    categoryId: 7,
    name: "Mixed Nuts",
    nameAr: "مكسرات مشكلة",
    icon: "🥜",
    caloriesPer100: 600,
    proteinPer100: 20,
    carbsPer100: 20,
    fatPer100: 50,
    sizeType: "FOOD",
  },

  // --- Fast Food (Category 8) ---
  {
    id: "ff1",
    categoryId: 8,
    name: "Burger",
    nameAr: "برجر",
    icon: "🍔",
    caloriesPer100: 295,
    proteinPer100: 14,
    carbsPer100: 24,
    fatPer100: 14,
    sizeType: "UNIT",
    weightPerUnit: 200,
  },
  {
    id: "ff2",
    categoryId: 8,
    name: "Pizza",
    nameAr: "بيتزا",
    icon: "🍕",
    caloriesPer100: 266,
    proteinPer100: 11,
    carbsPer100: 33,
    fatPer100: 10,
    sizeType: "UNIT",
    weightPerUnit: 150,
  },

  // --- Seafood (Category 9) ---
  {
    id: "sf1",
    categoryId: 9,
    name: "Shrimp",
    nameAr: "جمبري",
    icon: "🍤",
    caloriesPer100: 99,
    proteinPer100: 24,
    carbsPer100: 0.2,
    fatPer100: 0.3,
    sizeType: "FOOD",
    isRawCookedToggle: true,
  },

  // --- Dairy (Category 10) ---
  {
    id: "dy1",
    categoryId: 10,
    name: "Greek Yogurt",
    nameAr: "زبادي يوناني",
    icon: "🥣",
    caloriesPer100: 59,
    proteinPer100: 10,
    carbsPer100: 3.6,
    fatPer100: 0.4,
    sizeType: "UNIT",
    weightPerUnit: 150,
  },
  {
    id: "dy2",
    categoryId: 10,
    name: "Cheddar Cheese",
    nameAr: "جبنة شيدر",
    icon: "🧀",
    caloriesPer100: 402,
    proteinPer100: 25,
    carbsPer100: 1.3,
    fatPer100: 33,
    sizeType: "FOOD",
  },

  // --- Breakfast (Category 11) ---
  {
    id: "bf1",
    categoryId: 11,
    name: "Pancakes",
    nameAr: "بان كيك",
    icon: "🥞",
    caloriesPer100: 227,
    proteinPer100: 6.4,
    carbsPer100: 28,
    fatPer100: 9.7,
    sizeType: "UNIT",
    weightPerUnit: 100,
  },

  // --- Snacks (Category 12) ---
  {
    id: "sn1",
    categoryId: 12,
    name: "Popcorn",
    nameAr: "فشار",
    icon: "🍿",
    caloriesPer100: 387,
    proteinPer100: 13,
    carbsPer100: 78,
    fatPer100: 4.5,
    sizeType: "FOOD",
  },

  // --- Salads (Category 13) ---
  {
    id: "sl1",
    categoryId: 13,
    name: "Caesar Salad",
    nameAr: "سلطة سيزر",
    icon: "🥗",
    caloriesPer100: 150,
    proteinPer100: 5,
    carbsPer100: 8,
    fatPer100: 11,
    sizeType: "FOOD",
  },

  // --- Supplements (Category 17) ---
  {
    id: "sp1",
    categoryId: 17,
    name: "Whey Protein",
    nameAr: "واي بروتين",
    icon: "💪",
    caloriesPer100: 379,
    proteinPer100: 79,
    carbsPer100: 7,
    fatPer100: 4,
    sizeType: "SPOON",
    weightPerUnit: 30,
  },

  // --- Ramadan (Category 19) ---
  {
    id: "rm1",
    categoryId: 19,
    name: "Qatayef",
    nameAr: "قطايف",
    icon: "🥟",
    caloriesPer100: 330,
    proteinPer100: 6,
    carbsPer100: 55,
    fatPer100: 10,
    sizeType: "UNIT",
    weightPerUnit: 50,
  },

  // --- Traditional Egyptian (Category 20) ---
  {
    id: "eg1",
    categoryId: 20,
    name: "Feseekh",
    nameAr: "فسيخ",
    icon: "🐟",
    caloriesPer100: 200,
    proteinPer100: 22,
    carbsPer100: 0,
    fatPer100: 12,
    sizeType: "FOOD",
  },

  // --- Street Food (Category 14) ---
  {
    id: "st1",
    categoryId: 14,
    name: "Sweet Potato",
    nameAr: "بطاطا مشوية",
    icon: "🍠",
    caloriesPer100: 90,
    proteinPer100: 2,
    carbsPer100: 21,
    fatPer100: 0.2,
    sizeType: "UNIT",
    weightPerUnit: 150,
  },

  // --- Bakery (Category 15) ---
  {
    id: "bk1",
    categoryId: 15,
    name: "Croissant",
    nameAr: "كرواسون",
    icon: "🥐",
    caloriesPer100: 406,
    proteinPer100: 8,
    carbsPer100: 46,
    fatPer100: 21,
    sizeType: "UNIT",
    weightPerUnit: 60,
  },

  // --- Frozen Foods (Category 16) ---
  {
    id: "fz1",
    categoryId: 16,
    name: "Chicken Nuggets",
    nameAr: "ناجتس دجاج",
    icon: "🍗",
    caloriesPer100: 296,
    proteinPer100: 15,
    carbsPer100: 16,
    fatPer100: 20,
    sizeType: "UNIT",
    weightPerUnit: 20,
  },

  // --- Kids Meals (Category 18) ---
  {
    id: "km1",
    categoryId: 18,
    name: "Mac and Cheese",
    nameAr: "مكرونة بالجبنة",
    icon: "🧀",
    caloriesPer100: 164,
    proteinPer100: 7,
    carbsPer100: 22,
    fatPer100: 5,
    sizeType: "FOOD",
  }, // --- Eid Desserts / حلويات العيد ---
  {
    id: "eid1",
    categoryId: 5,
    name: "Kahk",
    nameAr: "كحك العيد",
    icon: "🍪",
    caloriesPer100: 480,
    proteinPer100: 6,
    carbsPer100: 60,
    fatPer100: 24,
    sizeType: "UNIT",
    weightPerUnit: 35,
  },
  {
    id: "eid2",
    categoryId: 5,
    name: "Petit Four",
    nameAr: "بيتي فور",
    icon: "🍪",
    caloriesPer100: 500,
    proteinPer100: 5,
    carbsPer100: 58,
    fatPer100: 28,
    sizeType: "UNIT",
    weightPerUnit: 20,
  },
  {
    id: "eid3",
    categoryId: 5,
    name: "Ghorayeba",
    nameAr: "غريبة",
    icon: "🍪",
    caloriesPer100: 520,
    proteinPer100: 4,
    carbsPer100: 55,
    fatPer100: 32,
    sizeType: "UNIT",
    weightPerUnit: 18,
  },
  {
    id: "eid4",
    categoryId: 5,
    name: "Biscuit",
    nameAr: "بسكويت العيد",
    icon: "🍪",
    caloriesPer100: 430,
    proteinPer100: 7,
    carbsPer100: 65,
    fatPer100: 16,
    sizeType: "UNIT",
    weightPerUnit: 15,
  },

  // --- Famous Egyptian Foods ---
  {
    id: "eg2",
    categoryId: 20,
    name: "Stuffed Pigeon",
    nameAr: "حمام محشي",
    icon: "🕊️",
    caloriesPer100: 290,
    proteinPer100: 22,
    carbsPer100: 10,
    fatPer100: 18,
    sizeType: "UNIT",
    weightPerUnit: 250,
  },
  {
    id: "eg3",
    categoryId: 20,
    name: "Alexandrian Hawawshi",
    nameAr: "حواوشي إسكندراني",
    icon: "🥙",
    caloriesPer100: 320,
    proteinPer100: 16,
    carbsPer100: 28,
    fatPer100: 18,
    sizeType: "FOOD",
  },
  {
    id: "eg4",
    categoryId: 20,
    name: "Rozz Meammar",
    nameAr: "أرز معمر",
    icon: "🍚",
    caloriesPer100: 250,
    proteinPer100: 6,
    carbsPer100: 30,
    fatPer100: 12,
    sizeType: "FOOD",
  },
  {
    id: "eg5",
    categoryId: 20,
    name: "Fatta",
    nameAr: "فتة",
    icon: "🍖",
    caloriesPer100: 260,
    proteinPer100: 15,
    carbsPer100: 25,
    fatPer100: 12,
    sizeType: "FOOD",
  },
  {
    id: "eg6",
    categoryId: 20,
    name: "Besara",
    nameAr: "بصارة",
    icon: "🥣",
    caloriesPer100: 110,
    proteinPer100: 6,
    carbsPer100: 15,
    fatPer100: 3,
    sizeType: "FOOD",
  },
  {
    id: "eg7",
    categoryId: 20,
    name: "Fried Eggplant",
    nameAr: "بتنجان مقلي",
    icon: "🍆",
    caloriesPer100: 190,
    proteinPer100: 2,
    carbsPer100: 10,
    fatPer100: 15,
    sizeType: "FOOD",
  },

  // --- Middle Eastern Foods ---
  {
    id: "me40",
    categoryId: 2,
    name: "Hummus",
    nameAr: "حمص",
    icon: "🧆",
    caloriesPer100: 166,
    proteinPer100: 8,
    carbsPer100: 14,
    fatPer100: 10,
    sizeType: "FOOD",
  },
  {
    id: "me41",
    categoryId: 2,
    name: "Mutabbal",
    nameAr: "متبل",
    icon: "🍆",
    caloriesPer100: 120,
    proteinPer100: 3,
    carbsPer100: 8,
    fatPer100: 8,
    sizeType: "FOOD",
  },
  {
    id: "me42",
    categoryId: 2,
    name: "Shish Tawook",
    nameAr: "شيش طاووق",
    icon: "🍢",
    caloriesPer100: 180,
    proteinPer100: 25,
    carbsPer100: 3,
    fatPer100: 7,
    sizeType: "FOOD",
  },
  {
    id: "me43",
    categoryId: 2,
    name: "Mixed Grill",
    nameAr: "مشاوي مشكلة",
    icon: "🍖",
    caloriesPer100: 270,
    proteinPer100: 22,
    carbsPer100: 4,
    fatPer100: 18,
    sizeType: "FOOD",
  },
  {
    id: "me44",
    categoryId: 2,
    name: "Chicken Kabsa",
    nameAr: "كبسة دجاج",
    icon: "🍛",
    caloriesPer100: 190,
    proteinPer100: 12,
    carbsPer100: 22,
    fatPer100: 6,
    sizeType: "FOOD",
  },
  {
    id: "me45",
    categoryId: 2,
    name: "Mandi Rice",
    nameAr: "مندي",
    icon: "🍚",
    caloriesPer100: 210,
    proteinPer100: 10,
    carbsPer100: 28,
    fatPer100: 7,
    sizeType: "FOOD",
  },

  // --- Breakfast Egyptian ---
  {
    id: "bf2",
    categoryId: 11,
    name: "Fried Egg Sandwich",
    nameAr: "ساندوتش بيض",
    icon: "🥪",
    caloriesPer100: 240,
    proteinPer100: 10,
    carbsPer100: 20,
    fatPer100: 12,
    sizeType: "UNIT",
    weightPerUnit: 120,
  },
  {
    id: "bf3",
    categoryId: 11,
    name: "Foul Sandwich",
    nameAr: "ساندوتش فول",
    icon: "🥙",
    caloriesPer100: 220,
    proteinPer100: 8,
    carbsPer100: 35,
    fatPer100: 5,
    sizeType: "UNIT",
    weightPerUnit: 150,
  },
  {
    id: "bf4",
    categoryId: 11,
    name: "Taameya Sandwich",
    nameAr: "ساندوتش طعمية",
    icon: "🧆",
    caloriesPer100: 290,
    proteinPer100: 10,
    carbsPer100: 30,
    fatPer100: 14,
    sizeType: "UNIT",
    weightPerUnit: 140,
  },
  {
    id: "c5",
    categoryId: 3,
    name: "Brown Rice",
    nameAr: "أرز بني",
    icon: "🍚",
    caloriesPer100: 112,
    proteinPer100: 2.6,
    carbsPer100: 23,
    fatPer100: 0.9,
    sizeType: "FOOD",
    isRawCookedToggle: true,
  },
  {
    id: "c6",
    categoryId: 3,
    name: "Pasta (Cooked)",
    nameAr: "مكرونة مسلوقة",
    icon: "🍝",
    caloriesPer100: 131,
    proteinPer100: 5,
    carbsPer100: 25,
    fatPer100: 1.1,
    sizeType: "FOOD",
  },
  {
    id: "c7",
    categoryId: 3,
    name: "Corn",
    nameAr: "ذرة",
    icon: "🌽",
    caloriesPer100: 86,
    proteinPer100: 3.2,
    carbsPer100: 19,
    fatPer100: 1.2,
    sizeType: "FOOD",
  },
  {
    id: "c8",
    categoryId: 3,
    name: "Quinoa",
    nameAr: "كينوا",
    icon: "🥣",
    caloriesPer100: 120,
    proteinPer100: 4.4,
    carbsPer100: 21,
    fatPer100: 1.9,
    sizeType: "FOOD",
    isRawCookedToggle: true,
  },
  {
    id: "c9",
    categoryId: 3,
    name: "Toast Bread",
    nameAr: "توست",
    icon: "🍞",
    caloriesPer100: 265,
    proteinPer100: 9,
    carbsPer100: 49,
    fatPer100: 3.2,
    sizeType: "UNIT",
    weightPerUnit: 30,
  },
  {
    id: "c10",
    categoryId: 3,
    name: "Sweet Potato",
    nameAr: "بطاطا حلوة",
    icon: "🍠",
    caloriesPer100: 86,
    proteinPer100: 1.6,
    carbsPer100: 20,
    fatPer100: 0.1,
    sizeType: "FOOD",
  },
  {
    id: "c12",
    categoryId: 3,
    name: "Lentils (Cooked)",
    nameAr: "عدس مطبوخ",
    icon: "🥣",
    caloriesPer100: 116,
    proteinPer100: 9,
    carbsPer100: 20,
    fatPer100: 0.4,
    sizeType: "FOOD",
  },

  // ─── Fruits & Veggies – Category 4 ───────────────────────
  {
    id: "fr2",
    categoryId: 4,
    name: "Banana",
    nameAr: "موز",
    icon: "🍌",
    caloriesPer100: 89,
    proteinPer100: 1.1,
    carbsPer100: 23,
    fatPer100: 0.3,
    sizeType: "UNIT",
    weightPerUnit: 120,
  },
  {
    id: "fr3",
    categoryId: 4,
    name: "Watermelon",
    nameAr: "بطيخ",
    icon: "🍉",
    caloriesPer100: 30,
    proteinPer100: 0.6,
    carbsPer100: 8,
    fatPer100: 0.2,
    sizeType: "FOOD",
  },
  {
    id: "fr4",
    categoryId: 4,
    name: "Mango",
    nameAr: "مانجو",
    icon: "🥭",
    caloriesPer100: 60,
    proteinPer100: 0.8,
    carbsPer100: 15,
    fatPer100: 0.4,
    sizeType: "FOOD",
  },
  {
    id: "fr5",
    categoryId: 4,
    name: "Grapes",
    nameAr: "عنب",
    icon: "🍇",
    caloriesPer100: 67,
    proteinPer100: 0.6,
    carbsPer100: 17,
    fatPer100: 0.4,
    sizeType: "FOOD",
  },
  {
    id: "v3",
    categoryId: 4,
    name: "Cucumber",
    nameAr: "خيار",
    icon: "🥒",
    caloriesPer100: 16,
    proteinPer100: 0.7,
    carbsPer100: 4,
    fatPer100: 0.1,
    sizeType: "FOOD",
  },
  {
    id: "v4",
    categoryId: 4,
    name: "Tomato",
    nameAr: "طماطم",
    icon: "🍅",
    caloriesPer100: 18,
    proteinPer100: 0.9,
    carbsPer100: 4,
    fatPer100: 0.2,
    sizeType: "FOOD",
  },
  {
    id: "v5",
    categoryId: 4,
    name: "Carrot",
    nameAr: "جزر",
    icon: "🥕",
    caloriesPer100: 41,
    proteinPer100: 0.9,
    carbsPer100: 10,
    fatPer100: 0.2,
    sizeType: "FOOD",
  },
  {
    id: "fr6",
    categoryId: 4,
    name: "Strawberry",
    nameAr: "فراولة",
    icon: "🍓",
    caloriesPer100: 32,
    proteinPer100: 0.7,
    carbsPer100: 8,
    fatPer100: 0.3,
    sizeType: "FOOD",
  },
  {
    id: "fr7",
    categoryId: 4,
    name: "Guava",
    nameAr: "جوافة",
    icon: "🍈",
    caloriesPer100: 68,
    proteinPer100: 2.6,
    carbsPer100: 14,
    fatPer100: 1,
    sizeType: "UNIT",
    weightPerUnit: 100,
  },

  // ─── Drinks – Category 6 ──────────────────────────────────
  {
    id: "d3",
    categoryId: 6,
    name: "Orange Juice",
    nameAr: "عصير برتقال",
    icon: "🍊",
    caloriesPer100: 45,
    proteinPer100: 0.7,
    carbsPer100: 10,
    fatPer100: 0.2,
    sizeType: "DRINK",
  },
  {
    id: "d4",
    categoryId: 6,
    name: "Green Tea",
    nameAr: "شاي أخضر",
    icon: "🍵",
    caloriesPer100: 1,
    proteinPer100: 0,
    carbsPer100: 0,
    fatPer100: 0,
    sizeType: "DRINK",
  },
  {
    id: "d5",
    categoryId: 6,
    name: "Cola",
    nameAr: "كولا",
    icon: "🥤",
    caloriesPer100: 42,
    proteinPer100: 0,
    carbsPer100: 10.6,
    fatPer100: 0,
    sizeType: "DRINK",
  },
  {
    id: "d6",
    categoryId: 6,
    name: "Black Tea",
    nameAr: "شاي أسود",
    icon: "☕",
    caloriesPer100: 1,
    proteinPer100: 0,
    carbsPer100: 0.2,
    fatPer100: 0,
    sizeType: "DRINK",
  },
  {
    id: "d7",
    categoryId: 6,
    name: "Lemon Mint",
    nameAr: "ليمون بالنعناع",
    icon: "🍋",
    caloriesPer100: 25,
    proteinPer100: 0,
    carbsPer100: 6,
    fatPer100: 0,
    sizeType: "DRINK",
  },
  {
    id: "d8",
    categoryId: 6,
    name: "Energy Drink",
    nameAr: "مشروب طاقة",
    icon: "⚡",
    caloriesPer100: 45,
    proteinPer100: 0,
    carbsPer100: 11,
    fatPer100: 0,
    sizeType: "DRINK",
  },
  {
    id: "d9",
    categoryId: 6,
    name: "Protein Shake",
    nameAr: "شيك بروتين",
    icon: "🥤",
    caloriesPer100: 70,
    proteinPer100: 10,
    carbsPer100: 5,
    fatPer100: 1.5,
    sizeType: "DRINK",
  },
  {
    id: "d10",
    categoryId: 6,
    name: "Ayran (Yogurt Drink)",
    nameAr: "عيران",
    icon: "🥛",
    caloriesPer100: 40,
    proteinPer100: 3,
    carbsPer100: 4,
    fatPer100: 1.5,
    sizeType: "DRINK",
  },

  // ─── Fast Food – Category 8 ───────────────────────────────
  {
    id: "ff3",
    categoryId: 8,
    name: "French Fries",
    nameAr: "بطاطس مقلية",
    icon: "🍟",
    caloriesPer100: 312,
    proteinPer100: 3.4,
    carbsPer100: 41,
    fatPer100: 15,
    sizeType: "FOOD",
  },
  {
    id: "ff4",
    categoryId: 8,
    name: "Hot Dog",
    nameAr: "هوت دوج",
    icon: "🌭",
    caloriesPer100: 290,
    proteinPer100: 11,
    carbsPer100: 22,
    fatPer100: 17,
    sizeType: "UNIT",
    weightPerUnit: 140,
  },
  {
    id: "ff5",
    categoryId: 8,
    name: "Chicken Sandwich",
    nameAr: "ساندوتش دجاج",
    icon: "🍗",
    caloriesPer100: 250,
    proteinPer100: 16,
    carbsPer100: 24,
    fatPer100: 10,
    sizeType: "UNIT",
    weightPerUnit: 180,
  },
  {
    id: "ff6",
    categoryId: 8,
    name: "Fried Chicken",
    nameAr: "دجاج مقلي",
    icon: "🍗",
    caloriesPer100: 320,
    proteinPer100: 22,
    carbsPer100: 12,
    fatPer100: 21,
    sizeType: "FOOD",
  },
  {
    id: "ff7",
    categoryId: 8,
    name: "Onion Rings",
    nameAr: "حلقات بصل",
    icon: "🧅",
    caloriesPer100: 376,
    proteinPer100: 5,
    carbsPer100: 38,
    fatPer100: 23,
    sizeType: "FOOD",
  },

  // ─── Seafood – Category 9 ─────────────────────────────────
  {
    id: "sf2",
    categoryId: 9,
    name: "Tuna (Canned)",
    nameAr: "تونة معلبة",
    icon: "🐟",
    caloriesPer100: 132,
    proteinPer100: 28,
    carbsPer100: 0,
    fatPer100: 1,
    sizeType: "FOOD",
  },
  {
    id: "sf3",
    categoryId: 9,
    name: "Salmon",
    nameAr: "سلمون",
    icon: "🍣",
    caloriesPer100: 208,
    proteinPer100: 20,
    carbsPer100: 0,
    fatPer100: 13,
    sizeType: "FOOD",
    isRawCookedToggle: true,
  },
  {
    id: "sf4",
    categoryId: 9,
    name: "Calamari",
    nameAr: "كلاماري",
    icon: "🦑",
    caloriesPer100: 175,
    proteinPer100: 15,
    carbsPer100: 8,
    fatPer100: 9,
    sizeType: "FOOD",
  },
  {
    id: "sf5",
    categoryId: 9,
    name: "Sardines",
    nameAr: "سردين",
    icon: "🐟",
    caloriesPer100: 208,
    proteinPer100: 25,
    carbsPer100: 0,
    fatPer100: 11,
    sizeType: "FOOD",
  },
  {
    id: "sf6",
    categoryId: 9,
    name: "Crab",
    nameAr: "كابوريا",
    icon: "🦀",
    caloriesPer100: 97,
    proteinPer100: 19,
    carbsPer100: 0,
    fatPer100: 2,
    sizeType: "FOOD",
  },
  {
    id: "sf7",
    categoryId: 9,
    name: "Fish Fillet (Baked)",
    nameAr: "فيليه سمك",
    icon: "🐠",
    caloriesPer100: 165,
    proteinPer100: 20,
    carbsPer100: 5,
    fatPer100: 7,
    sizeType: "FOOD",
  },

  // ─── Dairy – Category 10 ──────────────────────────────────
  {
    id: "dy3",
    categoryId: 10,
    name: "Labneh",
    nameAr: "لبنة",
    icon: "🧀",
    caloriesPer100: 190,
    proteinPer100: 10,
    carbsPer100: 4,
    fatPer100: 15,
    sizeType: "FOOD",
  },
  {
    id: "dy4",
    categoryId: 10,
    name: "Feta Cheese",
    nameAr: "جبنة فيتا",
    icon: "🧀",
    caloriesPer100: 264,
    proteinPer100: 14,
    carbsPer100: 4,
    fatPer100: 21,
    sizeType: "FOOD",
  },
  {
    id: "dy5",
    categoryId: 10,
    name: "Cottage Cheese",
    nameAr: "جبنة قريش",
    icon: "🥛",
    caloriesPer100: 98,
    proteinPer100: 11,
    carbsPer100: 3.4,
    fatPer100: 4.3,
    sizeType: "FOOD",
  },
  {
    id: "dy6",
    categoryId: 10,
    name: "Cream Cheese",
    nameAr: "كريم تشيز",
    icon: "🧀",
    caloriesPer100: 342,
    proteinPer100: 6,
    carbsPer100: 4,
    fatPer100: 34,
    sizeType: "FOOD",
  },
  {
    id: "dy7",
    categoryId: 10,
    name: "Low-Fat Yogurt",
    nameAr: "زبادي قليل الدسم",
    icon: "🥣",
    caloriesPer100: 56,
    proteinPer100: 5.7,
    carbsPer100: 6,
    fatPer100: 1.5,
    sizeType: "UNIT",
    weightPerUnit: 150,
  },
  {
    id: "dy8",
    categoryId: 10,
    name: "Mozzarella",
    nameAr: "موزاريلا",
    icon: "🧀",
    caloriesPer100: 280,
    proteinPer100: 20,
    carbsPer100: 2,
    fatPer100: 22,
    sizeType: "FOOD",
  },

  // ─── Breakfast – Category 11 ──────────────────────────────
  {
    id: "bf5",
    categoryId: 11,
    name: "Omelet (2 Eggs)",
    nameAr: "أومليت",
    icon: "🍳",
    caloriesPer100: 154,
    proteinPer100: 11,
    carbsPer100: 1,
    fatPer100: 12,
    sizeType: "UNIT",
    weightPerUnit: 100,
  },
  {
    id: "bf6",
    categoryId: 11,
    name: "Granola",
    nameAr: "جرانولا",
    icon: "🥣",
    caloriesPer100: 489,
    proteinPer100: 10,
    carbsPer100: 60,
    fatPer100: 22,
    sizeType: "FOOD",
  },
  {
    id: "bf7",
    categoryId: 11,
    name: "Corn Flakes",
    nameAr: "كورن فليكس",
    icon: "🥣",
    caloriesPer100: 357,
    proteinPer100: 7,
    carbsPer100: 84,
    fatPer100: 1,
    sizeType: "FOOD",
  },
  {
    id: "bf8",
    categoryId: 11,
    name: "Scrambled Eggs",
    nameAr: "بيض مخفوق",
    icon: "🍳",
    caloriesPer100: 148,
    proteinPer100: 10,
    carbsPer100: 1,
    fatPer100: 11,
    sizeType: "FOOD",
  },
  {
    id: "bf9",
    categoryId: 11,
    name: "Avocado Toast",
    nameAr: "توست أفوكادو",
    icon: "🥑",
    caloriesPer100: 220,
    proteinPer100: 5,
    carbsPer100: 18,
    fatPer100: 13,
    sizeType: "FOOD",
  },

  // ─── Snacks – Category 12 ─────────────────────────────────
  {
    id: "sn2",
    categoryId: 12,
    name: "Almonds",
    nameAr: "لوز",
    icon: "🫘",
    caloriesPer100: 579,
    proteinPer100: 21,
    carbsPer100: 22,
    fatPer100: 50,
    sizeType: "FOOD",
  },
  {
    id: "sn3",
    categoryId: 12,
    name: "Peanuts",
    nameAr: "فول سوداني",
    icon: "🥜",
    caloriesPer100: 567,
    proteinPer100: 26,
    carbsPer100: 16,
    fatPer100: 49,
    sizeType: "FOOD",
  },
  {
    id: "sn4",
    categoryId: 12,
    name: "Chips",
    nameAr: "شيبس",
    icon: "🥔",
    caloriesPer100: 536,
    proteinPer100: 7,
    carbsPer100: 53,
    fatPer100: 35,
    sizeType: "FOOD",
  },
  {
    id: "sn5",
    categoryId: 12,
    name: "Cashews",
    nameAr: "كاجو",
    icon: "🫘",
    caloriesPer100: 553,
    proteinPer100: 18,
    carbsPer100: 30,
    fatPer100: 44,
    sizeType: "FOOD",
  },
  {
    id: "sn6",
    categoryId: 12,
    name: "Protein Bar",
    nameAr: "بروتين بار",
    icon: "🍫",
    caloriesPer100: 380,
    proteinPer100: 30,
    carbsPer100: 35,
    fatPer100: 12,
    sizeType: "UNIT",
    weightPerUnit: 60,
  },
  {
    id: "sn7",
    categoryId: 12,
    name: "Rice Cakes",
    nameAr: "كيك أرز",
    icon: "🫓",
    caloriesPer100: 387,
    proteinPer100: 8,
    carbsPer100: 81,
    fatPer100: 3,
    sizeType: "UNIT",
    weightPerUnit: 10,
  },
  {
    id: "sn8",
    categoryId: 12,
    name: "Walnuts",
    nameAr: "جوز",
    icon: "🫘",
    caloriesPer100: 654,
    proteinPer100: 15,
    carbsPer100: 14,
    fatPer100: 65,
    sizeType: "FOOD",
  },

  // ─── Salads – Category 13 ─────────────────────────────────
  {
    id: "sl2",
    categoryId: 13,
    name: "Fattoush",
    nameAr: "فتوش",
    icon: "🥗",
    caloriesPer100: 90,
    proteinPer100: 2,
    carbsPer100: 12,
    fatPer100: 4,
    sizeType: "FOOD",
  },
  {
    id: "sl3",
    categoryId: 13,
    name: "Tabbouleh",
    nameAr: "تبولة",
    icon: "🥗",
    caloriesPer100: 75,
    proteinPer100: 2.5,
    carbsPer100: 10,
    fatPer100: 3,
    sizeType: "FOOD",
  },
  {
    id: "sl4",
    categoryId: 13,
    name: "Greek Salad",
    nameAr: "سلطة يونانية",
    icon: "🥗",
    caloriesPer100: 100,
    proteinPer100: 3,
    carbsPer100: 6,
    fatPer100: 7,
    sizeType: "FOOD",
  },
  {
    id: "sl5",
    categoryId: 13,
    name: "Coleslaw",
    nameAr: "كولسلو",
    icon: "🥗",
    caloriesPer100: 152,
    proteinPer100: 1.3,
    carbsPer100: 14,
    fatPer100: 10,
    sizeType: "FOOD",
  },
  {
    id: "sl6",
    categoryId: 13,
    name: "Green Salad",
    nameAr: "سلطة خضراء",
    icon: "🥬",
    caloriesPer100: 20,
    proteinPer100: 1.5,
    carbsPer100: 3,
    fatPer100: 0.3,
    sizeType: "FOOD",
  },
  {
    id: "sl7",
    categoryId: 13,
    name: "Egg Salad",
    nameAr: "سلطة بيض",
    icon: "🥗",
    caloriesPer100: 170,
    proteinPer100: 9,
    carbsPer100: 2,
    fatPer100: 14,
    sizeType: "FOOD",
  },

  // ─── Street Food – Category 14 ────────────────────────────
  {
    id: "st2",
    categoryId: 14,
    name: "Liver Sandwich",
    nameAr: "ساندوتش كبدة",
    icon: "🥙",
    caloriesPer100: 270,
    proteinPer100: 18,
    carbsPer100: 22,
    fatPer100: 12,
    sizeType: "UNIT",
    weightPerUnit: 150,
  },
  {
    id: "st3",
    categoryId: 14,
    name: "Falafel Wrap",
    nameAr: "ساندوتش طعمية",
    icon: "🧆",
    caloriesPer100: 290,
    proteinPer100: 10,
    carbsPer100: 32,
    fatPer100: 13,
    sizeType: "UNIT",
    weightPerUnit: 160,
  },
  {
    id: "st4",
    categoryId: 14,
    name: "Roasted Corn",
    nameAr: "ذرة مشوية",
    icon: "🌽",
    caloriesPer100: 130,
    proteinPer100: 4,
    carbsPer100: 28,
    fatPer100: 2,
    sizeType: "UNIT",
    weightPerUnit: 150,
  },
  {
    id: "st5",
    categoryId: 14,
    name: "Shawarma Wrap",
    nameAr: "شاورما لفة",
    icon: "🌯",
    caloriesPer100: 240,
    proteinPer100: 16,
    carbsPer100: 20,
    fatPer100: 11,
    sizeType: "UNIT",
    weightPerUnit: 200,
  },
  {
    id: "st6",
    categoryId: 14,
    name: "Ful Sandwich",
    nameAr: "ساندوتش فول بلدي",
    icon: "🥙",
    caloriesPer100: 210,
    proteinPer100: 8,
    carbsPer100: 33,
    fatPer100: 5,
    sizeType: "UNIT",
    weightPerUnit: 160,
  },

  // ─── Bakery – Category 15 ─────────────────────────────────
  {
    id: "bk2",
    categoryId: 15,
    name: "Muffin",
    nameAr: "مافن",
    icon: "🧁",
    caloriesPer100: 375,
    proteinPer100: 5,
    carbsPer100: 55,
    fatPer100: 15,
    sizeType: "UNIT",
    weightPerUnit: 80,
  },
  {
    id: "bk3",
    categoryId: 15,
    name: "Donut",
    nameAr: "دونات",
    icon: "🍩",
    caloriesPer100: 452,
    proteinPer100: 5,
    carbsPer100: 51,
    fatPer100: 25,
    sizeType: "UNIT",
    weightPerUnit: 60,
  },
  {
    id: "bk4",
    categoryId: 15,
    name: "Baguette",
    nameAr: "خبز فرنسي",
    icon: "🥖",
    caloriesPer100: 272,
    proteinPer100: 9,
    carbsPer100: 52,
    fatPer100: 1.5,
    sizeType: "FOOD",
  },
  {
    id: "bk5",
    categoryId: 15,
    name: "Chocolate Cake",
    nameAr: "كيكة شوكولاتة",
    icon: "🍰",
    caloriesPer100: 371,
    proteinPer100: 5,
    carbsPer100: 50,
    fatPer100: 17,
    sizeType: "FOOD",
  },
  {
    id: "bk6",
    categoryId: 15,
    name: "Cheese Pie",
    nameAr: "فطيرة جبنة",
    icon: "🥧",
    caloriesPer100: 320,
    proteinPer100: 10,
    carbsPer100: 35,
    fatPer100: 16,
    sizeType: "UNIT",
    weightPerUnit: 120,
  },

  // ─── Frozen Foods – Category 16 ──────────────────────────
  {
    id: "fz2",
    categoryId: 16,
    name: "Frozen Pizza",
    nameAr: "بيتزا مجمدة",
    icon: "🍕",
    caloriesPer100: 230,
    proteinPer100: 9,
    carbsPer100: 28,
    fatPer100: 9,
    sizeType: "FOOD",
  },
  {
    id: "fz3",
    categoryId: 16,
    name: "Fish Sticks",
    nameAr: "عصايا سمك",
    icon: "🐟",
    caloriesPer100: 250,
    proteinPer100: 14,
    carbsPer100: 20,
    fatPer100: 12,
    sizeType: "UNIT",
    weightPerUnit: 25,
  },
  {
    id: "fz4",
    categoryId: 16,
    name: "Frozen Burger Patty",
    nameAr: "برجر مجمد",
    icon: "🍔",
    caloriesPer100: 290,
    proteinPer100: 18,
    carbsPer100: 8,
    fatPer100: 21,
    sizeType: "UNIT",
    weightPerUnit: 100,
  },
  {
    id: "fz5",
    categoryId: 16,
    name: "Frozen Vegetables",
    nameAr: "خضار مجمد",
    icon: "🥦",
    caloriesPer100: 40,
    proteinPer100: 3,
    carbsPer100: 7,
    fatPer100: 0.3,
    sizeType: "FOOD",
  },
  {
    id: "fz6",
    categoryId: 16,
    name: "Pizza Rolls",
    nameAr: "رولز بيتزا",
    icon: "🥟",
    caloriesPer100: 295,
    proteinPer100: 9,
    carbsPer100: 33,
    fatPer100: 14,
    sizeType: "UNIT",
    weightPerUnit: 30,
  },

  // ─── Supplements – Category 17 ───────────────────────────
  {
    id: "sp2",
    categoryId: 17,
    name: "Creatine",
    nameAr: "كرياتين",
    icon: "💊",
    caloriesPer100: 0,
    proteinPer100: 0,
    carbsPer100: 0,
    fatPer100: 0,
    sizeType: "SPOON",
    weightPerUnit: 5,
  },
  {
    id: "sp3",
    categoryId: 17,
    name: "Casein Protein",
    nameAr: "كازين بروتين",
    icon: "🥛",
    caloriesPer100: 370,
    proteinPer100: 75,
    carbsPer100: 10,
    fatPer100: 3,
    sizeType: "SPOON",
    weightPerUnit: 30,
  },
  {
    id: "sp4",
    categoryId: 17,
    name: "Mass Gainer",
    nameAr: "ماس جينر",
    icon: "💪",
    caloriesPer100: 380,
    proteinPer100: 20,
    carbsPer100: 70,
    fatPer100: 3,
    sizeType: "SPOON",
    weightPerUnit: 75,
  },
  {
    id: "sp5",
    categoryId: 17,
    name: "BCAA",
    nameAr: "بي سي أيه أيه",
    icon: "🧪",
    caloriesPer100: 40,
    proteinPer100: 10,
    carbsPer100: 0,
    fatPer100: 0,
    sizeType: "SPOON",
    weightPerUnit: 10,
  },
  {
    id: "sp6",
    categoryId: 17,
    name: "Fish Oil",
    nameAr: "أوميجا 3",
    icon: "🐟",
    caloriesPer100: 900,
    proteinPer100: 0,
    carbsPer100: 0,
    fatPer100: 100,
    sizeType: "UNIT",
    weightPerUnit: 1,
  },

  // ─── Kids Meals – Category 18 ─────────────────────────────
  {
    id: "km2",
    categoryId: 18,
    name: "Chicken Fingers",
    nameAr: "أصابع دجاج",
    icon: "🍗",
    caloriesPer100: 265,
    proteinPer100: 16,
    carbsPer100: 14,
    fatPer100: 16,
    sizeType: "UNIT",
    weightPerUnit: 25,
  },
  {
    id: "km3",
    categoryId: 18,
    name: "Cheese Pizza Slice",
    nameAr: "بيتزا جبنة",
    icon: "🍕",
    caloriesPer100: 260,
    proteinPer100: 12,
    carbsPer100: 32,
    fatPer100: 9,
    sizeType: "UNIT",
    weightPerUnit: 100,
  },
  {
    id: "km4",
    categoryId: 18,
    name: "Mini Hot Dog",
    nameAr: "هوت دوج صغير",
    icon: "🌭",
    caloriesPer100: 270,
    proteinPer100: 10,
    carbsPer100: 20,
    fatPer100: 16,
    sizeType: "UNIT",
    weightPerUnit: 80,
  },
  {
    id: "km5",
    categoryId: 18,
    name: "Cereal",
    nameAr: "سيريال",
    icon: "🥣",
    caloriesPer100: 370,
    proteinPer100: 8,
    carbsPer100: 80,
    fatPer100: 3,
    sizeType: "FOOD",
  },
  {
    id: "km6",
    categoryId: 18,
    name: "Peanut Butter Sandwich",
    nameAr: "ساندوتش زبدة فول",
    icon: "🥪",
    caloriesPer100: 380,
    proteinPer100: 12,
    carbsPer100: 35,
    fatPer100: 22,
    sizeType: "UNIT",
    weightPerUnit: 100,
  },

  // ─── Ramadan Foods – Category 19 ─────────────────────────
  {
    id: "rm2",
    categoryId: 19,
    name: "Sambousa",
    nameAr: "سمبوسة",
    icon: "🥟",
    caloriesPer100: 350,
    proteinPer100: 10,
    carbsPer100: 30,
    fatPer100: 20,
    sizeType: "UNIT",
    weightPerUnit: 40,
  },
  {
    id: "rm3",
    categoryId: 19,
    name: "Harira Soup",
    nameAr: "شوربة حريرة",
    icon: "🥣",
    caloriesPer100: 80,
    proteinPer100: 5,
    carbsPer100: 12,
    fatPer100: 2,
    sizeType: "FOOD",
  },
  {
    id: "rm4",
    categoryId: 19,
    name: "Kunafa (Ramadan)",
    nameAr: "كنافة رمضان",
    icon: "🍯",
    caloriesPer100: 450,
    proteinPer100: 5,
    carbsPer100: 60,
    fatPer100: 22,
    sizeType: "FOOD",
  },
  {
    id: "rm5",
    categoryId: 19,
    name: "Date & Milk",
    nameAr: "تمر ولبن",
    icon: "🌴",
    caloriesPer100: 130,
    proteinPer100: 2,
    carbsPer100: 28,
    fatPer100: 1.5,
    sizeType: "FOOD",
  },
  {
    id: "rm6",
    categoryId: 19,
    name: "Vimto Juice",
    nameAr: "فيمتو",
    icon: "🍷",
    caloriesPer100: 60,
    proteinPer100: 0,
    carbsPer100: 15,
    fatPer100: 0,
    sizeType: "DRINK",
  },
  {
    id: "rm7",
    categoryId: 19,
    name: "Ful Medames (Ramadan)",
    nameAr: "فول رمضاني",
    icon: "🥣",
    caloriesPer100: 120,
    proteinPer100: 8,
    carbsPer100: 22,
    fatPer100: 1,
    sizeType: "FOOD",
  },

  // ─── Eid Desserts – Category 21 ──────────────────────────
  {
    id: "eid5",
    categoryId: 21,
    name: "Kahk (Eid)",
    nameAr: "كحك العيد",
    icon: "🍪",
    caloriesPer100: 480,
    proteinPer100: 6,
    carbsPer100: 60,
    fatPer100: 24,
    sizeType: "UNIT",
    weightPerUnit: 35,
  },
  {
    id: "eid6",
    categoryId: 21,
    name: "Ghorayeba",
    nameAr: "غريبة",
    icon: "🍪",
    caloriesPer100: 520,
    proteinPer100: 4,
    carbsPer100: 55,
    fatPer100: 32,
    sizeType: "UNIT",
    weightPerUnit: 18,
  },
  {
    id: "eid7",
    categoryId: 21,
    name: "Petit Four",
    nameAr: "بيتي فور",
    icon: "🍪",
    caloriesPer100: 500,
    proteinPer100: 5,
    carbsPer100: 58,
    fatPer100: 28,
    sizeType: "UNIT",
    weightPerUnit: 20,
  },
  {
    id: "eid8",
    categoryId: 21,
    name: "Meshabek",
    nameAr: "مشبك",
    icon: "🍩",
    caloriesPer100: 390,
    proteinPer100: 4,
    carbsPer100: 70,
    fatPer100: 12,
    sizeType: "FOOD",
  },
  {
    id: "eid9",
    categoryId: 21,
    name: "Luqaimat",
    nameAr: "لقيمات",
    icon: "🫓",
    caloriesPer100: 350,
    proteinPer100: 5,
    carbsPer100: 55,
    fatPer100: 14,
    sizeType: "UNIT",
    weightPerUnit: 15,
  },
  {
    id: "eid10",
    categoryId: 21,
    name: "Ma'amoul",
    nameAr: "معمول",
    icon: "🍪",
    caloriesPer100: 430,
    proteinPer100: 5,
    carbsPer100: 60,
    fatPer100: 20,
    sizeType: "UNIT",
    weightPerUnit: 40,
  },

  // ─── Grills – Category 22 ─────────────────────────────────
  {
    id: "gr1",
    categoryId: 22,
    name: "Grilled Chicken",
    nameAr: "دجاج مشوي",
    icon: "🍗",
    caloriesPer100: 195,
    proteinPer100: 29,
    carbsPer100: 0,
    fatPer100: 8,
    sizeType: "FOOD",
    isRawCookedToggle: true,
  },
  {
    id: "gr2",
    categoryId: 22,
    name: "Beef Steak",
    nameAr: "ستيك لحم",
    icon: "🥩",
    caloriesPer100: 271,
    proteinPer100: 26,
    carbsPer100: 0,
    fatPer100: 18,
    sizeType: "FOOD",
    isRawCookedToggle: true,
  },
  {
    id: "gr3",
    categoryId: 22,
    name: "Kofta",
    nameAr: "كفتة",
    icon: "🍢",
    caloriesPer100: 280,
    proteinPer100: 16,
    carbsPer100: 4,
    fatPer100: 22,
    sizeType: "FOOD",
  },
  {
    id: "gr4",
    categoryId: 22,
    name: "Lamb Chops",
    nameAr: "ريش ضاني",
    icon: "🍖",
    caloriesPer100: 294,
    proteinPer100: 25,
    carbsPer100: 0,
    fatPer100: 21,
    sizeType: "FOOD",
    isRawCookedToggle: true,
  },
  {
    id: "gr5",
    categoryId: 22,
    name: "Shish Tawook",
    nameAr: "شيش طاووق",
    icon: "🍢",
    caloriesPer100: 180,
    proteinPer100: 25,
    carbsPer100: 3,
    fatPer100: 7,
    sizeType: "FOOD",
  },
  {
    id: "gr6",
    categoryId: 22,
    name: "Mixed Grill Platter",
    nameAr: "مشاوي مشكلة",
    icon: "🍖",
    caloriesPer100: 270,
    proteinPer100: 22,
    carbsPer100: 4,
    fatPer100: 18,
    sizeType: "FOOD",
  },
  {
    id: "gr7",
    categoryId: 22,
    name: "Grilled Corn",
    nameAr: "ذرة مشوية",
    icon: "🌽",
    caloriesPer100: 96,
    proteinPer100: 3.4,
    carbsPer100: 21,
    fatPer100: 1.5,
    sizeType: "UNIT",
    weightPerUnit: 150,
  },

  // ─── Rice Dishes – Category 23 ────────────────────────────
  {
    id: "rd1",
    categoryId: 23,
    name: "Chicken Kabsa",
    nameAr: "كبسة دجاج",
    icon: "🍛",
    caloriesPer100: 190,
    proteinPer100: 12,
    carbsPer100: 22,
    fatPer100: 6,
    sizeType: "FOOD",
  },
  {
    id: "rd2",
    categoryId: 23,
    name: "Biryani",
    nameAr: "برياني",
    icon: "🍛",
    caloriesPer100: 180,
    proteinPer100: 10,
    carbsPer100: 25,
    fatPer100: 5,
    sizeType: "FOOD",
  },
  {
    id: "rd3",
    categoryId: 23,
    name: "Mandi Rice",
    nameAr: "أرز مندي",
    icon: "🍚",
    caloriesPer100: 210,
    proteinPer100: 10,
    carbsPer100: 28,
    fatPer100: 7,
    sizeType: "FOOD",
  },
  {
    id: "rd4",
    categoryId: 23,
    name: "Maqluba",
    nameAr: "مقلوبة",
    icon: "🍚",
    caloriesPer100: 200,
    proteinPer100: 9,
    carbsPer100: 26,
    fatPer100: 8,
    sizeType: "FOOD",
  },
  {
    id: "rd5",
    categoryId: 23,
    name: "Rozz Meammar",
    nameAr: "أرز معمر",
    icon: "🍚",
    caloriesPer100: 250,
    proteinPer100: 6,
    carbsPer100: 30,
    fatPer100: 12,
    sizeType: "FOOD",
  },
  {
    id: "rd6",
    categoryId: 23,
    name: "Fried Rice",
    nameAr: "أرز مقلي",
    icon: "🍳",
    caloriesPer100: 163,
    proteinPer100: 5,
    carbsPer100: 28,
    fatPer100: 4,
    sizeType: "FOOD",
  },
  {
    id: "rd7",
    categoryId: 23,
    name: "Rice with Vermicelli",
    nameAr: "أرز بالشعيرية",
    icon: "🍚",
    caloriesPer100: 150,
    proteinPer100: 3,
    carbsPer100: 30,
    fatPer100: 2,
    sizeType: "FOOD",
  },

  // ─── Sandwiches – Category 24 ─────────────────────────────
  {
    id: "sw1",
    categoryId: 24,
    name: "Tuna Sandwich",
    nameAr: "ساندوتش تونة",
    icon: "🥪",
    caloriesPer100: 210,
    proteinPer100: 16,
    carbsPer100: 22,
    fatPer100: 7,
    sizeType: "UNIT",
    weightPerUnit: 150,
  },
  {
    id: "sw2",
    categoryId: 24,
    name: "Club Sandwich",
    nameAr: "كلوب ساندوتش",
    icon: "🥪",
    caloriesPer100: 260,
    proteinPer100: 14,
    carbsPer100: 26,
    fatPer100: 11,
    sizeType: "UNIT",
    weightPerUnit: 200,
  },
  {
    id: "sw3",
    categoryId: 24,
    name: "Cheese Sandwich",
    nameAr: "ساندوتش جبنة",
    icon: "🧀",
    caloriesPer100: 290,
    proteinPer100: 12,
    carbsPer100: 28,
    fatPer100: 14,
    sizeType: "UNIT",
    weightPerUnit: 120,
  },
  {
    id: "sw4",
    categoryId: 24,
    name: "Chicken Shawarma Wrap",
    nameAr: "شاورما دجاج رول",
    icon: "🌯",
    caloriesPer100: 225,
    proteinPer100: 17,
    carbsPer100: 20,
    fatPer100: 9,
    sizeType: "UNIT",
    weightPerUnit: 200,
  },
  {
    id: "sw5",
    categoryId: 24,
    name: "Beef Shawarma Wrap",
    nameAr: "شاورما لحم رول",
    icon: "🌯",
    caloriesPer100: 250,
    proteinPer100: 16,
    carbsPer100: 22,
    fatPer100: 11,
    sizeType: "UNIT",
    weightPerUnit: 200,
  },
  {
    id: "sw6",
    categoryId: 24,
    name: "Falafel Sandwich",
    nameAr: "ساندوتش فلافل",
    icon: "🧆",
    caloriesPer100: 280,
    proteinPer100: 10,
    carbsPer100: 32,
    fatPer100: 13,
    sizeType: "UNIT",
    weightPerUnit: 160,
  },
  {
    id: "sw7",
    categoryId: 24,
    name: "Sausage Sandwich",
    nameAr: "ساندوتش سجق",
    icon: "🥪",
    caloriesPer100: 310,
    proteinPer100: 12,
    carbsPer100: 24,
    fatPer100: 18,
    sizeType: "UNIT",
    weightPerUnit: 140,
  },
];

// Helper for backward compatibility (maps flat foods back into categories for UI)
export const category = CATEGORIES.map((cat) => ({
  ...cat,
  foods: FOODS.filter((food) => food.categoryId === cat.id),
}));
